name: load_secrets

on: workflow_dispatch

jobs:
  test_env:
    environment: TEST_SECRET
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
          
      - name: Test env vars for python
        run: python -c 'import os;print(os.environ)'
        env:
          DEMO_SECRET: ${{ secrets.DEMO_SECRET}}
